### ISSUE TITLE
Enlarge introduction to dependency diagrams

### ISSUE THREAD

**Issue by PabRod** [escience-academy/lesson-parallel-python#11]
## Actions

- [x] Explain how to read dependency diagrams
- [ ] Use a consistent style (currently the functions and the pea soup examples follow different styles)

It is also a good opportunity to introduce the (very often unknown) concept of function.

## Misc

Related #6

**Comment by jhidding** [comment]
The text itself is mainly targeted at the teacher. I assume familiarity with functions. I'll add that to the prereqs
