### ISSUE TITLE
Are both examples in Ch1 not serial?

### ISSUE THREAD

**Issue by PabRod** [escience-academy/lesson-parallel-python#12]
According to chapter 1, this is serial:

```{python}
x = some_input
for i in range(n):
  x = f(x)
print(x)
```

and this is parallel:

```{python}
for i in range(n):
  x[i] = f(some_input[i])
print(collect(x))
```

I find this rather confusing.

**Comment by jhidding** [comment]
The dependencies allow for parallel computation, the snippet is not yet concurrent

**Comment by jhidding** [comment]
But I agree it could use a bit more flesh on the bones ;)

**Comment by PabRod** [comment]
Oh, it's not the abstraction what I find confusing. In my opinion the distinction between parallel and parallelizable is too subtle. After all, this is our very first example.
