### ISSUE TITLE
what is Dask

### ISSUE THREAD

**Issue by fnattino** [escience-academy/lesson-parallel-python#20]
Dask is now introduced in chapter 4 from all its sub-modules (arrays, bags, etc.). Might be worth it to add a line to define Dask (something like "graph execution engine") and explain that the execution happens lazily (we always need to call the compute method).

**Comment by PabRod** [comment]
Fully agree. 

I'll add that Dask is:

- Mentioned for the first time in chapter 1.
- Used for the first time in chapter 2.

**Comment by fnattino** [comment]
Yes! Also in chapter 4, I am missing a bit why one should use `dask` `array`/`bag`/`delayed`.  I think it would be nice to have a line to clarify what each submodule is helpful for, at the beginning of each section.

**Comment by jhidding** [comment]
Ok, the Dask module should be introduced in the first chapter, because it is central to the entire lesson. I've added a table setting out the different components in Dask at the front of the "Dask abstractions" chapter.
