### ISSUE TITLE
Profiling of dask.bag implementation of `calc_pi`

### ISSUE THREAD

**Issue by fnattino** [escience-academy/lesson-parallel-python#30]
FIXME: profile the `dask.bag`-based pi calculator.

**Comment by fnattino** [comment]
@jhidding where you thinking about providing the results of the profiling here? Or adding a challenge to profile this against the other pi calculator versions?

**Comment by jhidding** [comment]
I decided to just drop it, profiling is important but it would take too much time to do it for every case.
